// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Kzy4jil4P5oD1WoVdyUSF6La2avBoWU',
    appId: '1:33963227390:web:0084d36b8fbcbb047b8daf',
    messagingSenderId: '33963227390',
    projectId: 'my-cool-project-ef700',
    authDomain: 'my-cool-project-ef700.firebaseapp.com',
    storageBucket: 'my-cool-project-ef700.firebasestorage.app',
    measurementId: 'G-L2MHY8QN6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJt1xSUGhmLTAmeOK1N3WQRVo89XgRDs',
    appId: '1:33963227390:android:719e6c8aca7aa3fa7b8daf',
    messagingSenderId: '33963227390',
    projectId: 'my-cool-project-ef700',
    storageBucket: 'my-cool-project-ef700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZSWZiQCVvUQungEkBXkC1orXy6ZYNDuM',
    appId: '1:33963227390:ios:b71e3a7f81f576937b8daf',
    messagingSenderId: '33963227390',
    projectId: 'my-cool-project-ef700',
    storageBucket: 'my-cool-project-ef700.firebasestorage.app',
    iosBundleId: 'com.example.mobBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZSWZiQCVvUQungEkBXkC1orXy6ZYNDuM',
    appId: '1:33963227390:ios:b71e3a7f81f576937b8daf',
    messagingSenderId: '33963227390',
    projectId: 'my-cool-project-ef700',
    storageBucket: 'my-cool-project-ef700.firebasestorage.app',
    iosBundleId: 'com.example.mobBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Kzy4jil4P5oD1WoVdyUSF6La2avBoWU',
    appId: '1:33963227390:web:564620782e74aae37b8daf',
    messagingSenderId: '33963227390',
    projectId: 'my-cool-project-ef700',
    authDomain: 'my-cool-project-ef700.firebaseapp.com',
    storageBucket: 'my-cool-project-ef700.firebasestorage.app',
    measurementId: 'G-ZRCVYNLQSE',
  );
}
